plugins {
    id "com.android.application"
}

android {
    namespace "com.hdhub.xdownload.anyvideo.bestdownloader"
    compileSdk 34

    defaultConfig {
        applicationId "com.hdhub.xdownload.anyvideo.bestdownloader"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            manifest.srcFile "${rootProject.projectDir}/video/video/resources/AndroidManifest.xml"
            java.srcDirs = [
                "${rootProject.projectDir}/video/video/sources"
            ]
            res.srcDirs = [
                "${rootProject.projectDir}/video/video/resources/res"
            ]
            assets.srcDirs = [
                "${rootProject.projectDir}/video/video/resources/assets"
            ]
            aidl.srcDirs = []
            jni.srcDirs = []
            renderscript.srcDirs = []
        }
    }

    packaging {
        resources {
            excludes += [
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/LICENSE.md",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt",
                "META-INF/NOTICE.md",
                "META-INF/*.kotlin_module"
            ]
        }
    }
}

dependencies {
    implementation "androidx.multidex:multidex:2.0.1"
}
